### ISSUE TITLE
Hello - I have a question about the VerifAI issue you raised in January: "### Fuzz testing using Scenic"

### ISSUE THREAD

**Issue by dorondru** [junjihashimoto/sixel#8]
I noticed no one resolved that issue. 

I'm trying to build it too but scenic files have syntax errors (or did they use an older scenic version?). Like "ahead by" seems to be invalid (now "offset by"?),  or "ego = ToyotaPrius at spot, with roadDeviation (-10, 10) deg",  in intersection_crash.sc, is a syntax error (again the token "with").

I noticed you complained about a runtime error (that issue is still open on GitHub). I have 2 questions, if I may:
1. How did you solve the syntax errors I mentioned above.
2. Are you still getting that runtime error? If so then I won't waste anymore time on it.

Thank you
-Doron

**Comment by junjihashimoto** [comment]
@dorondru 
Hello,

I couldn't solve it after all.（I didn't debug it.）
Other samples didn't work either.
This project does not have enough CI.
I think it is difficult to use continuously.

So, I am developping webots-binding for haskell, because it reduces runtime errors.
https://github.com/cyberbotics/HsWebots
